VIA_ENABLE		= yes
VIAL_ENABLE		= yes
VIAL_INSECURE	= yes

MOUSEKEY_ENABLE     	= yes
BOOTMAGIC_ENABLE    	= yes
TAP_DANCE_ENABLE    	= yes
MACROS_ENABLED      	= yes

SERIAL_DRIVER           = vendor

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360

